apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container-scan-staged-release
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: Release Readiness
      jobs:
        - Container-scan
        - policy-check-release-readiness
    - name: Quality Assurance
      jobs:
        - policy-check-approval
    - name: Staging
      jobs:
        - smoke-tests
    - name: Production
      jobs:
        - prod-smoke-tests
jobs:
  policy-check-release-readiness:
    needs: Container-scan
    uses: cloudbees-io/policy-utils/.cloudbees/workflows/by-context.yaml@lt-test
    with:
      checkpoint-type: stage
      input-data: ${{ needs.container-scan.outputs.policy-subject }}
      checkpoint-position: within
      checkpoint-name: Release Readiness
    secrets: inherit
  smoke-tests:
    steps:
      - run: echo "Running smoke tests on staging"
        uses: docker://alpine:3.20
  prod-smoke-tests:
    steps:
      - uses: docker://alpine:3.20
        run: echo "Running production smoke tests"
  policy-check-approval:
    needs:
      - Container-scan
    uses: cloudbees-io/policy-utils/.cloudbees/workflows/by-context.yaml@lt-test
    with:
      checkpoint-type: stage
      input-data: ${{ needs.container-scan.outputs.policy-subject }}
      checkpoint-position: within
      checkpoint-name: Quality Assurance
  Container-scan:
    outputs:
      policy-subject: ${{ steps.trivy-scan.outputs.policy-subject }}
    steps:
      - with:
          url: ${{ vars.JFROG_URL }}
          username: ${{ vars.JFROG_ACTIONS_USERNAME }}
          password: ${{ secrets.JFROG_ACTIONS_PASSWORD }}
          file-path: /cloudbees/workspace/golang-alpine.tar
          artifactory-path: test-generic-repo/jfrogtest/golang-alpine.tar
        uses: cloudbees-io/jfrog-artifactory-download-file@v1
        name: jfrog-actions-workflow-download
      - with:
          binary-tar-path: /cloudbees/workspace/golang-alpine.tar
        uses: cloudbees-io/trivy-plugin@v1
        name: trivy-scan
        id: trivy-scan
      - run: |
          echo "Policy Subject: ${{ steps.trivy-scan.outputs.policy-subject }}"
        uses: docker://alpine:3.20
        name: Print Trivy Policy Subject
